export const API = {
  EXCELDATA: "/stg_trn_data/",
  FETCHERRORDATA: "/err_trn_data_tab/",
  UPDATEERRORDATA: "/delete_err_trn/",
  GETHIER2DATA: "/lov_item_dtl/",
  GETLOCATIONDATA: "/location_validation/",
  FETCHCONFIGDATA: "/system_config_tab/",
  UPDATECONFIGDATA: "/sys_conf/",
  DAILYCOUNTDATA: "/count_pending/",
  STAGECOUNTDATA: "/count_stg_trn/",
  ERRORCOUNTDATA: "/count_trn/",
  FETCHDAILYRECDATA: "/daily_rec/",
  FETCHERRSTAGESATA: "/retrieve_err_stg_data/",
  UPDATETRANSACTIONREVERSAL: "/trn_data_rev/",
  FETCHTRANSACTIONREVERSAL: "/trn_data_history/",
  CANCELTRANSACTIONREVERSAL: "/cancel/",
  FETCHITEMLOCATIONDATA: "/item_loc_data/",
  UPDATECOSTANDVAR: "/cost_update_stg_trn/",
  FETCHGLACCOUNT:"/gl_account_tab/",  
  UPDATEGLACCOUNT:"/GL_ACCOUNT_update/",
  GETGLDATA:"/currency_gl/",
  INSERTGLDATA:"/GL_ACCOUNT_create/",
  FETCHSTGFIN:"/Retrieve_stg_fin/",
  FETCHTRNTYPE :"/trn_type_dtl/",
  FETCHTRNTYPELIST: "/trn_type_dtl_list/",
  FETCHDAILYVIEW:"/Daily_view/",
  FETCHSUBLEDGERCOST:"/subledger_cost/",
  CREATESYSCONF:"/system_config_creation/",
  FETCHGLPRIMARY:"/primary_gl/",
  FETCHHIER:"/HIER_tab/",
  FETCHHIER2:"/HIER2_tab/",
  FETCHHIER3:"/HIER3_tab/",
  FETCHUDA:"/UDA_tab/",
  FETCHILH:"/item_list_head_tab/",
  FETCHITEMPRT:"/ITEM_PARENT_tab/",
  FETCHDIF:"/DIFF_tab/",
  FETCHSKU:"/SKU_tab/",
  FECTCHALLOCITEMS:"/allocated_items/",
  INSERTLIKEITEM: "/Insert_LikeItem/",
};
