/*Dashboard Actions Start */
export const GET_DAILYCOUNT_REQUEST = "GET_DAILYCOUNT_REQUEST";
export const GET_DAILYCOUNT_SUCCESS = "GET_DAILYCOUNT_SUCCESS";
export const GET_DAILYCOUNT_ERROR = "GET_DAILYCOUNT_ERROR";

export const GET_STAGECOUNT_REQUEST = "GET_STAGECOUNT_REQUEST";
export const GET_STAGECOUNT_SUCCESS = "GET_STAGECOUNT_SUCCESS";
export const GET_STAGECOUNT_ERROR = "GET_STAGECOUNT_ERROR";

export const GET_ERRORCOUNT_REQUEST = "GET_ERRORCOUNT_REQUEST";
export const GET_ERRORCOUNT_SUCCESS = "GET_ERRORCOUNT_SUCCESS";
export const GET_ERRORCOUNT_ERROR = "GET_ERRORCOUNT_ERROR";

/*Dashboard Actions End */

/* Global Actions Start */
export const POST_CURRENCYGL_REQUEST = "POST_CURRENCYGL_REQUEST";
export const POST_CURRENCYGL_SUCCESS = "POST_CURRENCYGL_SUCCESS";
export const POST_CURRENCYGL_ERROR = "POST_CURRENCYGL_ERROR";

/* Global Action End */
/* Account Tab Start */
export const POST_GLACCOUNTTAB_REQUEST = "POST_GLACCOUNTTAB_REQUEST";
export const POST_GLACCOUNTTAB_SUCCESS = "POST_GLACCOUNTTAB_SUCCESS";
export const POST_GLACCOUNTTAB_ERROR = "POST_GLACCOUNTTAB_ERROR";

export const POST_GLACCOUNTUPD_REQUEST = "POST_GLACCOUNTUPD_REQUEST";
export const POST_GLACCOUNTUPD_SUCCESS = "POST_GLACCOUNTUPD_SUCCESS";
export const POST_GLACCOUNTUPD_ERROR = "POST_GLACCOUNTUPD_ERROR";
/* Account Tab End */

/* Error Tab Start */
export const POST_ERRTABDATA_REQUEST = "POST_ERRTABDATA_REQUEST";
export const POST_ERRTABDATA_SUCCESS = "POST_ERRTABDATA_SUCCESS";
export const POST_ERRTABDATA_ERROR = "POST_ERRTABDATA_ERROR";
/* Error Tab End */
