export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING = "RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";
export const GET_HIER2DATA_REQUEST = "GET_HIER2DATA_REQUEST";
export const GET_HIER2DATA_SUCCESS = "GET_HIER2DATA_SUCCESS";
export const GET_HIER2DATA_ERROR = "GET_HIER2DATA_ERROR";
export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_ERROR = "GET_LOCATIONDATA_ERROR";
export const GET_SYSTEMCONFIG_REQUEST = "GET_SYSTEMCONFIG_REQUEST";
export const GET_SYSTEMCONFIG_SUCCESS = "GET_SYSTEMCONFIG_SUCCESS";
export const GET_SYSTEMCONFIG_ERROR = "GET_SYSTEMCONFIG_ERROR";
export const POST_SYSTEMCONFIG_REQUEST = "POST_SYSTEMCONFIG_REQUEST";
export const POST_SYSTEMCONFIG_SUCCESS = "POST_SYSTEMCONFIG_SUCCESS";
export const POST_SYSTEMCONFIG_ERROR = "POST_SYSTEMCONFIG_ERROR";
export const RESET_SYSTEMCONFIG = "RESET_SYSTEMCONFIG";
export const GET_DAILYCOUNT_REQUEST = "GET_DAILYCOUNT_REQUEST";
export const GET_DAILYCOUNT_SUCCESS = "GET_DAILYCOUNT_SUCCESS";
export const GET_DAILYCOUNT_ERROR = "GET_DAILYCOUNT_ERROR";
export const GET_STAGECOUNT_REQUEST = "GET_STAGECOUNT_REQUEST";
export const GET_STAGECOUNT_SUCCESS = "GET_STAGECOUNT_SUCCESS";
export const GET_STAGECOUNT_ERROR = "GET_STAGECOUNT_ERROR";
export const GET_ERRORCOUNT_REQUEST = "GET_ERRORCOUNT_REQUEST";
export const GET_ERRORCOUNT_SUCCESS = "GET_ERRORCOUNT_SUCCESS";
export const GET_ERRORCOUNT_ERROR = "GET_ERRORCOUNT_ERROR";
export const GET_DAILY_SKU_ROLLUPDATA_REQUEST = "GET_DAILY_SKU_ROLLUPDATA_REQUEST";
export const GET_DAILY_SKU_ROLLUPDATA_SUCCESS = "GET_HIER2DATA_SUCCESS";
export const GET_DAILY_SKU_ROLLUPDATA_ERROR = "GET_DAILY_SKU_ROLLUPDATA_ERROR";
export const GET_HIER1RECDATA_REQUEST = "GET_HIER1RECDATA_REQUEST";
export const GET_HIER1RECDATA_SUCCESS = "GET_HIER1RECDATA_SUCCESS";
export const GET_HIER1RECDATA_ERROR = "GET_HIER1RECDATA_ERROR";
export const GET_LOCATIONRECDATA_REQUEST = "GET_LOCATIONRECDATA_REQUEST";
export const GET_LOCATIONRECDATA_SUCCESS = "GET_LOCATIONRECDATA_SUCCESS";
export const GET_LOCATIONRECDATA_ERROR = "GET_LOCATIONRECDATA_ERROR";
export const GET_INQUIRYDATA_REQUEST = "GET_INQUIRYDATA_REQUEST";
export const GET_INQUIRYDATA_SUCCESS = "GET_INQUIRYDATA_SUCCESS";
export const GET_INQUIRYDATA_ERROR = "GET_INQUIRYDATA_ERROR";
export const RESET_INQUIRY = "RESET_INQUIRY";
export const GET_TRANSACTIONREVERSAL_REQUEST = "GET_TRANSACTIONREVERSAL_REQUEST";
export const GET_TRANSACTIONREVERSAL_SUCCESS = "GET_TRANSACTIONREVERSAL_SUCCESS";
export const GET_TRANSACTIONREVERSAL_ERROR = "GET_TRANSACTIONREVERSAL_ERROR";
export const POST_TRANSACTIONREVERSAL_REQUEST = "POST_TRANSACTIONREVERSAL_REQUEST";
export const POST_TRANSACTIONREVERSAL_SUCCESS = "POST_TRANSACTIONREVERSAL_SUCCESS";
export const POST_TRANSACTIONREVERSAL_ERROR = "POST_TRANSACTIONREVERSAL_ERROR";
export const POST_TRANSACTIONCANCEL_REQUEST = "POST_TRANSACTIONCANCEL_REQUEST";
export const POST_TRANSACTIONCANCEL_SUCCESS = "POST_TRANSACTIONCANCEL_SUCCESS";
export const POST_TRANSACTIONCANCEL_ERROR = "POST_TRANSACTIONCANCEL_ERROR";
export const RESET_TRANSACTIONREVERSAL = "RESET_TRANSACTIONREVERSAL";

export const GET_COSTCHANGE_REQUEST = "GET_COSTCHANGE_REQUEST";
export const GET_COSTCHANGE_SUCCESS = "GET_COSTCHANGE_SUCCESS";
export const GET_COSTCHANGE_ERROR = "GET_COSTCHANGE_ERROR";
export const POST_COSTCHANGE_REQUEST = "POST_COSTCHANGE_REQUEST";
export const POST_COSTCHANGE_SUCCESS = "POST_COSTCHANGE_SUCCESS";
export const POST_COSTCHANGE_ERROR = "POST_COSTCHANGE_ERROR";


export const GET_GLACCOUNT_REQUEST = "GET_GLACCOUNT_REQUEST";
export const GET_GLACCOUNT_SUCCESS = "GET_GLACCOUNT_SUCCESS";
export const GET_GLACCOUNT_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNT_REQUEST = "POST_GLACCOUNT_REQUEST";
export const POST_GLACCOUNT_SUCCESS = "POST_GLACCOUNT_SUCCESS";
export const POST_GLACCOUNT_ERROR = "POST_GLACCOUNT_ERROR";
export const GET_GLACCOUNTCREATION_REQUEST = "GET_GLACCOUNTCREATION_REQUEST";
export const GET_GLACCOUNTCREATION_SUCCESS = "GET_GLACCOUNTCREATION_SUCCESS";
export const GET_GLACCOUNTCREATION_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNTCREATION_REQUEST = "POST_GLACCOUNTCREATION_REQUEST";
export const POST_GLACCOUNTCREATION_SUCCESS = "POST_GLACCOUNTCREATION_SUCCESS";
export const POST_GLACCOUNTCREATION_ERROR = "POST_GLACCOUNTCREATION_ERROR";
export const GET_GLCURRENCY_REQUEST = "GET_GLCURRENCY_REQUEST";
export const GET_GLCURRENCY_SUCCESS="GET_GLCURRENCY_SUCCESS";
export const GET_GLCURRENCY_ERROR="GET_GLCURRENCY_ERROR";
export const POST_GLCREATION_REQUEST = "POST_GLCREATION_REQUEST";
export const POST_GLCREATION_SUCCESS = "POST_GLCREATION_SUCCESS";
export const POST_GLCREATION_ERROR = "POST_GLCREATION_ERROR";

export const GET_FINANCEINTERFACE_REQUEST = "GET_FINANCEINTERFACE_REQUEST";
export const GET_FINANCEINTERFACE_SUCCESS = "GET_FINANCEINTERFACE_SUCCESS";
export const GET_FINANCEINTERFACE_ERROR = "GET_FINANCEINTERFACE_ERROR";

export const GET_DAILYVIEW_REQUEST = "GET_DAILYVIEW_REQUEST";
export const GET_DAILYVIEW_SUCCESS = "GET_DAILYVIEW_SUCCESS";
export const GET_DAILYVIEW_ERROR = "GET_DAILYVIEW_ERROR";

export const GET_SUBLEDGERCOST_REQUEST = "GET_SUBLEDGERCOST_REQUEST";
export const GET_SUBLEDGERCOST_SUCCESS = "GET_SUBLEDGERCOST_SUCCESS";
export const GET_SUBLEDGERCOST_ERROR = "GET_SUBLEDGERCOST_ERROR";

export const POST_SYSCONFIGCREATION_REQUEST = "POST_SYSCONFIGCREATION_REQUEST";
export const POST_SYSCONFIGCREATION_SUCCESS = "POST_SYSCONFIGCREATION_SUCCESS";
export const POST_SYSCONFIGCREATION_ERROR = "POST_SYSCONFIGCREATION_ERROR";
export const GET_GLPRIMARY_REQUEST = "GET_GLPRIMARY_REQUEST";
export const GET_GLPRIMARY_SUCCESS = "GET_GLPRIMARY_SUCCESS";
export const GET_GLPRIMARY_ERROR = "GET_GLPRIMARY_ERROR";

// like item mapping
export const GET_HIER_REQUEST = "GET_HIER_REQUEST";
export const GET_HIER_SUCCESS = "GET_HIER_SUCCESS";
export const GET_HIER_ERROR = "GET_HIER_ERROR";
export const GET_HIER2_REQUEST = "GET_HIER2_REQUEST";
export const GET_HIER2_SUCCESS = "GET_HIER2_SUCCESS";
export const GET_HIER2_ERROR = "GET_HIER2_ERROR";
export const GET_HIER3_REQUEST = "GET_HIER3_REQUEST";
export const GET_HIER3_SUCCESS = "GET_HIER3_SUCCESS";
export const GET_HIER3_ERROR = "GET_HIER3_ERROR";
export const GET_UDA_REQUEST = "GET_UDA_REQUEST";
export const GET_UDA_SUCCESS = "GET_UDA_SUCCESS";
export const GET_UDA_ERROR = "GET_UDA_ERROR";
export const GET_ITEM_LIST_HEAD_REQUEST = "GET_ITEM_LIST_HEAD_REQUEST";
export const GET_ITEM_LIST_HEAD_SUCCESS = "GET_ITEM_LIST_HEAD_SUCCESS";
export const GET_ITEM_LIST_HEAD_ERROR = "GET_ITEM_LIST_HEAD_ERROR";
export const GET_ITEMPARENT_REQUEST = "GET_ITEMPARENT_REQUEST";
export const GET_ITEMPARENT_SUCCESS = "GET_ITEMPARENT_SUCCESS";
export const GET_ITEMPARENT_ERROR = "GET_ITEMPARENT_ERROR";
export const GET_DIFF_REQUEST = "GET_DIFF_REQUEST";
export const GET_DIFF_SUCCESS = "GET_DIFF_SUCCESS";
export const GET_DIFF_ERROR = "GET_DIFF_ERROR";
export const GET_SKU_REQUEST = "GET_SKU_REQUEST";
export const GET_SKU_SUCCESS = "GET_SKU_SUCCESS";
export const GET_SKU_ERROR = "GET_SKU_ERROR";
export const GET_ALLOC_ITEMS_REQUEST = "GET_ALLOC_ITEMS_REQUEST";
export const GET_ALLOC_ITEMS_SUCCESS = "GET_ALLOC_ITEMS_SUCCESS";
export const GET_ALLOC_ITEMS_ERROR = "GET_ALLOC_ITEMS_ERROR";
//INSERT LIKE ITEM
export const POST_LIKE_INSERT_REQUEST = "POST_LIKE_INSERT_REQUEST";
export const POST_LIKE_INSERT_SUCCESS = "POST_LIKE_INSERT_SUCCESS";
export const POST_LIKE_INSERT_ERROR = "POST_LIKE_INSERT_ERROR";

//ALLOCATION IDS FOR HEADER
export const GET_ALLOC_ID_REQUEST = "GET_ALLOC_ID_REQUEST";
export const GET_ALLOC_ID_SUCCESS = "GET_ALLOC_ID_SUCCESS";
export const GET_ALLOC_ID_ERROR = "GET_ALLOC_ID_ERROR";

//ALLOCATION IDS FOR HEADER
export const POST_ALLOC_HDETAILS_REQUEST = "POST_ALLOC_HDETAILS_REQUEST";
export const POST_ALLOC_HDETAILS_SUCCESS = "POST_ALLOC_HDETAILS_SUCCESS";
export const POST_ALLOC_HDETAILS_ERROR = "POST_ALLOC_HDETAILS_ERROR";